name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md

  pull_request:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md

  workflow_call:
    inputs:
      build-artifacts:
        type: boolean
        default: false
        required: true

jobs:
  build-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: src/ReactUi/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: src/ReactUi

      - name: ESLint
        run: npm run lint
        working-directory: src/ReactUi

      - name: Build React application
        run: npm run build
        env:
          VITE_GITHUB_URL: ${{ github.server_url }}/${{ github.repository }}
          VITE_DOCUMENTATION_URL: ${{ github.server_url }}/${{ github.repository }}/wiki
          VITE_BUG_REPORT_URL: ${{ github.server_url }}/${{ github.repository }}/issues
          VITE_FEATURE_REQUEST_URL: ${{ github.server_url }}/${{ github.repository }}/issues
          VITE_TOKEN_ENDPOINT: ${{ env.TOKEN_ENDPOINT }}
          VITE_LOGOUT_ENDPOINT: ${{ env.LOGOUT_ENDPOINT }}
          VITE_REDIRECT_URI: ${{ env.REDIRECT_URI }}
          VITE_CLIENT_ID: ${{ env.CLIENT_ID }}
        working-directory: src/ReactUi

      - name: Cache frontend build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ui-build
          path: src/ReactUi/dist

  build-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Install .NET
        uses: actions/setup-dotnet@v3

      - name: Restore solution
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Test solution
        run: dotnet test --no-build --configuration Release

      - name: Publish application
        run: |
          dotnet publish --configuration Release --runtime win-x86 --self-contained --output ./publish
        working-directory: ./src/Web/

      - name: Cache backend build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: server-build
          path: ./src/Web/publish
          if-no-files-found: error

  build:
    runs-on: ubuntu-latest
    needs: [build-ui, build-server]
    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: Download UI build artifacts
        uses: actions/download-artifact@v2
        with:
          name: ui-build
          path: ui-build
      
      - name: Download server build artifacts  
        uses: actions/download-artifact@v2
        with:
          name: server-build
          path: server-build

      - name: Copy UI files to server
        run: |
          mkdir -p server-build/wwwroot
          cp -r ui-build/* server-build/wwwroot
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: server-build
