name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md

  pull_request:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md

  workflow_call:
    inputs:
      build-artifacts:
        type: boolean
        default: false
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: src/ReactUi/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: src/ReactUi

      - name: ESLint
        run: npm run lint
        working-directory: src/ReactUi

      - name: Build React application
        run: npm run build
        working-directory: src/ReactUi

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Install .NET
        uses: actions/setup-dotnet@v3

      - name: Restore solution
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Test solution
        run: dotnet test --no-build --configuration Release

      - name: Publish application
        run: |
          dotnet publish --configuration Release --runtime win-x86 --self-contained --output ./publish
        working-directory: ./src/Web/

      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: publish
          path: ./src/Web/publish
          if-no-files-found: error
