name: Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: ./build.yml

  deploy:
    runs-on: self-hosted
    needs: build
    environment: production
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ vars.BUILD_ARTIFACT }}
          path: ${{ runner.temp }}

      - name: Unzip build artifact
        run: |
          unzip ${{ runner.temp }}/*.zip -d ${{ runner.temp }}/bin
        working-directory: ${{ runner.temp }}

      - name: JSON file transform
        uses: tnikFi/json-file-transform@v1
        with:
          files: ${{ runner.temp }}/bin/**/appsettings.json
          key-value-pairs: |
            Serilog.MinimumLevel.Override.Microsoft = Warning
            Serilog.WriteTo.1.Args.path = ${{ vars.LOG_FILE_PATH }}
            Discord.BotToken = ${{ secrets.DISCORD_BOT_TOKEN }}
            ConnectionStrings.DefaultConnection = ${{ secrets.DB_CONNECTION_STRING }}
            Authentication.Oauth.ClientSecret = ${{ secrets.OAUTH_CLIENT_SECRET }}
            Authentication.Oauth.ClientId = ${{ vars.CLIENT_ID }}
            Authentication.Oauth.RedirectUri = ${{ vars.REDIRECT_URI }}
            Authentication.Jwt.Issuer = ${{ vars.JWT_ISSUER }}
            Authentication.Jwt.Audience = ${{ vars.JWT_AUDIENCE }}
            Authentication.Jwt.SigningKey = ${{ secrets.JWT_SIGNING_KEY }}

      - name: Stop the Kestrel service
        run: systemctl stop ${{ vars.SERVICE_NAME }}

      - name: Clean up old files
        run: |
          rm -rf ${{ vars.SITE_ROOT }}/*

      - name: Copy new files
        run: |
          cp -r ${{ runner.temp }}/bin/* ${{ vars.SITE_ROOT }}

      - name: Start the Kestrel service
        run: systemctl start ${{ vars.SERVICE_NAME }}
